name: Sync to GitLab
 
on:
  push:
    branches: [ master ]
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Setup GitLab API
      uses: jasonetco/actions-setup-git@v2
      with:
        gitlab_token: ${{ secrets.GITLAB_TOKEN }}
        repository: 'Nicolasking007/CDN.git'
        ref: master
 
    - name: Push to GitLab
      run: |
        git config --global user.name "${{ secrets.GITLAB_TOKEN }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote set-url origin "https://gitlab.com/Nicolasking007/CDN.git"
        git push origin master
